### ISSUE TITLE
ModuleNotFoundError: No module named 'irc'

### ISSUE THREAD

**Issue by Agaros007** [milandamen/Discord-IRC-Python#8]
**Hello, sorry to disturbe you...**

Error Message:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from ircc import *
  File "C:\BattleArena\battlearena\Discord\ircc.py", line 1, in <module>
    import irc
ModuleNotFoundError: No module named 'irc'

**But in the Package list its installed. Any idea?**

Package            Version
------------------ -----------
discord.py         1.6.0
irc                19.0.1

**Comment by milandamen** [comment]
Have you checked that the package is installed for the correct python version? (like using pip3 instead of pip if you're using python3).

**Comment by Agaros007** [comment]
i had 2 Python versions installed and now i got to work Python 3.8.... But now i get this Message:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from ircc import *
  File "C:\BattleArena\battlearena\Discord\ircc.py", line 8, in <module>
    class IRC(irc.bot.SingleServerIRCBot):
AttributeError: module 'irc' has no attribute 'bot'

**Comment by Agaros007** [comment]
sorry im just a total beginner and dosnt have that much python experience

**Comment by milandamen** [comment]
Did you install the correct irc library? This bot uses this library: https://pypi.org/project/irc/

So you would install with `pip3 install irc`

**Comment by Agaros007** [comment]
yes he found the irc lib but the 

AttributeError: module 'irc' has no attribute 'bot'

looks like he cant find the attrubute 'bot' like it isnt the right lib or something is missing

**Comment by Agaros007** [comment]
![Uploading py.JPG…]()

**Comment by Agaros007** [comment]
![bot](https://user-images.githubusercontent.com/38462508/114020931-6731ad00-9870-11eb-9748-b56501e8ab4a.JPG)

**Comment by Agaros007** [comment]
![py](https://user-images.githubusercontent.com/38462508/114020962-70bb1500-9870-11eb-99b6-a0b3a07138f3.JPG)

**Comment by milandamen** [comment]
Weird. The irc library still has that bot package though. I don't know how I can further help you, because I also don't know much about the python package systems.

**Comment by Agaros007** [comment]
Found a fix. i just added 

**import irc.bot**

to the 

**ircc.py**

and now its working. very weird. now the next have a solution :)

**Comment by milandamen** [comment]
But ircc.py already has that import on line 1? https://github.com/milandamen/Discord-IRC-Python/blob/master/ircc.py

**Comment by Agaros007** [comment]
yes i know, and now it looks like this:
import irc
import re
import irc.bot

and thats working for me... dont ask me why
